/* eslint-disable */
// WARNING: DO NOT EDIT ATALL ATALL. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-2",
  aws_cognito_identity_pool_id:
    "ap-southeast-2:c7e81aa2-d6f0-48a1-bd0b-77cabef4b185",
  aws_cognito_region: "ap-southeast-2",
  aws_user_pools_id: "ap-southeast-2_H6gXnU3RL",
  aws_user_pools_web_client_id: "39l5r6d36j5dqluhif64rgfqrq",
  oauth: {},
};

export default awsmobile;
