/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:c7e81aa2-d6f0-48a1-bd0b-77cabef4b185",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_H6gXnU3RL",
    "aws_user_pools_web_client_id": "39l5r6d36j5dqluhif64rgfqrq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://igcymv7ctrcqpk4rrctaju7ia4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rinjmbyt2ffa3o26og2wkydnyq",
    "aws_user_files_s3_bucket": "amplifyappdc58ef470208433c9692d491c69bc18865742-dev",
    "aws_user_files_s3_bucket_region": "ap-southeast-2"
};


export default awsmobile;
